name: Mean stack Training Coderbase
on:
  push:
    branches: '*'
  pull_request:
    branches: [ develop , main ]

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name : Install dependencies
        run: npm i
      - name : Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
        run: npm run test