name: Mean stack Training Coderbase
on:
  push:
    branches: '*'
  pull_request:
    branches: [ develop , main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      env:
        DATABASE_URL: { { secrets.DATABASE_URL } }
        JWT_PRIVATE_KEY: { { secrets.JWT_PRIVATE_KEY } }
      - uses: actions/checkout@v2
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name : Install dependencies
        run: npm i
      - name : Run tests
        run: npm run test